/* This code was AUTOMATICALLY generated.
 * --> EDIT WITH CARE! <--
 */

/**
 * @file TimesTool_Q2.c
 * @author TimesTool, Version 1.3 beta, April, 2007 (build 2461) <www.timestool.com>
 * @brief Generated by: rudolfaf
 * @date Tue May 16 22:55:11 CEST 2023
 * - with Target:          brickos
 * 
 */

#include "TimesTool_Q2.h"
#include "brickos_interface.h"
#include "TimesTool_Q2_global.h"
#include "TimesTool_Q2_init.h"
/**
 * @name Task identifiers (tid).
 */
#define tid_offset 200
#define tid_NOP tid_offset+0

/**
 * Location identifiers, also offsets into
 * location array.
 */
#define PERIODIC_TASKS_START 0

char release_list[NB_TASK]={ 0,0,0,0,0,0,0,0,0};


wakeup_t task_release(wakeup_t data) {
  if(release_list[data]) {
    switch (data) { 
    default: return true;
  }
  } else
  return false;
}

wakeup_t task_complete(wakeup_t tid) {
  switch(tid) { 
  }
  return true;
}

/**
 * Constant values
 */

/**
 * Clock variables
 * Ordered: global first, then local clocks for each process.
 */
time_t clock_PERIODIC_TASKS_x;
/**
 * Integer variables
 */
int PERIODIC_TASKS_t_A_RecordOn=0;
int PERIODIC_TASKS_t_A_RecordOff=5;
int PERIODIC_TASKS_t_A_ProcessVideo=0;
int PERIODIC_TASKS_t_B_RecordOn=0;
int PERIODIC_TASKS_t_B_RecordOff=5;
int PERIODIC_TASKS_t_B_ProcessVideo=0;
int PERIODIC_TASKS_t_C_RecordOn=0;
int PERIODIC_TASKS_t_C_RecordOff=5;
int PERIODIC_TASKS_t_C_ProcessVideo=0;
int* IVARS[NB_VAR] ={&PERIODIC_TASKS_t_A_RecordOn,&PERIODIC_TASKS_t_A_RecordOff,&PERIODIC_TASKS_t_A_ProcessVideo,&PERIODIC_TASKS_t_B_RecordOn,&PERIODIC_TASKS_t_B_RecordOff,&PERIODIC_TASKS_t_B_ProcessVideo,&PERIODIC_TASKS_t_C_RecordOn,&PERIODIC_TASKS_t_C_RecordOff,&PERIODIC_TASKS_t_C_ProcessVideo};

void COPY2LOCAL( int tid, int instance ) {
  switch( tid ) {
  }
};

/**
 * Evaluate guards on transition trn.
 * @param trn Transition id
 * @return true if guard satisfied, false otherwise.
 */
bool eval_guard(int trn) {
  switch(trn) {
  case 0: return (rdClock(PERIODIC_TASKS_x)==PERIODIC_TASKS_t_A_RecordOn);
  case 1: return (rdClock(PERIODIC_TASKS_x)==PERIODIC_TASKS_t_A_RecordOff);
  case 2: return (rdClock(PERIODIC_TASKS_x)==PERIODIC_TASKS_t_A_ProcessVideo);
  case 3: return (rdClock(PERIODIC_TASKS_x)==PERIODIC_TASKS_t_B_RecordOn);
  case 4: return (rdClock(PERIODIC_TASKS_x)==PERIODIC_TASKS_t_B_RecordOff);
  case 5: return (rdClock(PERIODIC_TASKS_x)==PERIODIC_TASKS_t_B_ProcessVideo);
  case 6: return (rdClock(PERIODIC_TASKS_x)==PERIODIC_TASKS_t_C_RecordOn);
  case 7: return (rdClock(PERIODIC_TASKS_x)==PERIODIC_TASKS_t_C_RecordOff);
  case 8: return (rdClock(PERIODIC_TASKS_x)==PERIODIC_TASKS_t_C_ProcessVideo);
  }
  return false;
}

/**
 * Perform assignments on transition trn.
 * @param trn Transition id.
 */
void assign(int trn) {
  switch(trn) {
  case 0: 
    setClock(PERIODIC_TASKS_x,0);
    PERIODIC_TASKS_t_A_RecordOff=PERIODIC_TASKS_t_A_RecordOff-PERIODIC_TASKS_t_A_RecordOn;
    PERIODIC_TASKS_t_A_ProcessVideo=PERIODIC_TASKS_t_A_ProcessVideo-PERIODIC_TASKS_t_A_RecordOn;
    PERIODIC_TASKS_t_B_RecordOn=PERIODIC_TASKS_t_B_RecordOn-PERIODIC_TASKS_t_A_RecordOn;
    PERIODIC_TASKS_t_B_RecordOff=PERIODIC_TASKS_t_B_RecordOff-PERIODIC_TASKS_t_A_RecordOn;
    PERIODIC_TASKS_t_B_ProcessVideo=PERIODIC_TASKS_t_B_ProcessVideo-PERIODIC_TASKS_t_A_RecordOn;
    PERIODIC_TASKS_t_C_RecordOn=PERIODIC_TASKS_t_C_RecordOn-PERIODIC_TASKS_t_A_RecordOn;
    PERIODIC_TASKS_t_C_RecordOff=PERIODIC_TASKS_t_C_RecordOff-PERIODIC_TASKS_t_A_RecordOn;
    PERIODIC_TASKS_t_C_ProcessVideo=PERIODIC_TASKS_t_C_ProcessVideo-PERIODIC_TASKS_t_A_RecordOn;
    PERIODIC_TASKS_t_A_RecordOn=25; break;
  case 1: 
    setClock(PERIODIC_TASKS_x,0);
    PERIODIC_TASKS_t_A_RecordOn=PERIODIC_TASKS_t_A_RecordOn-PERIODIC_TASKS_t_A_RecordOff;
    PERIODIC_TASKS_t_A_ProcessVideo=PERIODIC_TASKS_t_A_ProcessVideo-PERIODIC_TASKS_t_A_RecordOff;
    PERIODIC_TASKS_t_B_RecordOn=PERIODIC_TASKS_t_B_RecordOn-PERIODIC_TASKS_t_A_RecordOff;
    PERIODIC_TASKS_t_B_RecordOff=PERIODIC_TASKS_t_B_RecordOff-PERIODIC_TASKS_t_A_RecordOff;
    PERIODIC_TASKS_t_B_ProcessVideo=PERIODIC_TASKS_t_B_ProcessVideo-PERIODIC_TASKS_t_A_RecordOff;
    PERIODIC_TASKS_t_C_RecordOn=PERIODIC_TASKS_t_C_RecordOn-PERIODIC_TASKS_t_A_RecordOff;
    PERIODIC_TASKS_t_C_RecordOff=PERIODIC_TASKS_t_C_RecordOff-PERIODIC_TASKS_t_A_RecordOff;
    PERIODIC_TASKS_t_C_ProcessVideo=PERIODIC_TASKS_t_C_ProcessVideo-PERIODIC_TASKS_t_A_RecordOff;
    PERIODIC_TASKS_t_A_RecordOff=25; break;
  case 2: 
    setClock(PERIODIC_TASKS_x,0);
    PERIODIC_TASKS_t_A_RecordOn=PERIODIC_TASKS_t_A_RecordOn-PERIODIC_TASKS_t_A_ProcessVideo;
    PERIODIC_TASKS_t_A_RecordOff=PERIODIC_TASKS_t_A_RecordOff-PERIODIC_TASKS_t_A_ProcessVideo;
    PERIODIC_TASKS_t_B_RecordOn=PERIODIC_TASKS_t_B_RecordOn-PERIODIC_TASKS_t_A_ProcessVideo;
    PERIODIC_TASKS_t_B_RecordOff=PERIODIC_TASKS_t_B_RecordOff-PERIODIC_TASKS_t_A_ProcessVideo;
    PERIODIC_TASKS_t_B_ProcessVideo=PERIODIC_TASKS_t_B_ProcessVideo-PERIODIC_TASKS_t_A_ProcessVideo;
    PERIODIC_TASKS_t_C_RecordOn=PERIODIC_TASKS_t_C_RecordOn-PERIODIC_TASKS_t_A_ProcessVideo;
    PERIODIC_TASKS_t_C_RecordOff=PERIODIC_TASKS_t_C_RecordOff-PERIODIC_TASKS_t_A_ProcessVideo;
    PERIODIC_TASKS_t_C_ProcessVideo=PERIODIC_TASKS_t_C_ProcessVideo-PERIODIC_TASKS_t_A_ProcessVideo;
    PERIODIC_TASKS_t_A_ProcessVideo=25; break;
  case 3: 
    setClock(PERIODIC_TASKS_x,0);
    PERIODIC_TASKS_t_A_RecordOn=PERIODIC_TASKS_t_A_RecordOn-PERIODIC_TASKS_t_B_RecordOn;
    PERIODIC_TASKS_t_A_RecordOff=PERIODIC_TASKS_t_A_RecordOff-PERIODIC_TASKS_t_B_RecordOn;
    PERIODIC_TASKS_t_A_ProcessVideo=PERIODIC_TASKS_t_A_ProcessVideo-PERIODIC_TASKS_t_B_RecordOn;
    PERIODIC_TASKS_t_B_RecordOff=PERIODIC_TASKS_t_B_RecordOff-PERIODIC_TASKS_t_B_RecordOn;
    PERIODIC_TASKS_t_B_ProcessVideo=PERIODIC_TASKS_t_B_ProcessVideo-PERIODIC_TASKS_t_B_RecordOn;
    PERIODIC_TASKS_t_C_RecordOn=PERIODIC_TASKS_t_C_RecordOn-PERIODIC_TASKS_t_B_RecordOn;
    PERIODIC_TASKS_t_C_RecordOff=PERIODIC_TASKS_t_C_RecordOff-PERIODIC_TASKS_t_B_RecordOn;
    PERIODIC_TASKS_t_C_ProcessVideo=PERIODIC_TASKS_t_C_ProcessVideo-PERIODIC_TASKS_t_B_RecordOn;
    PERIODIC_TASKS_t_B_RecordOn=25; break;
  case 4: 
    setClock(PERIODIC_TASKS_x,0);
    PERIODIC_TASKS_t_A_RecordOn=PERIODIC_TASKS_t_A_RecordOn-PERIODIC_TASKS_t_B_RecordOff;
    PERIODIC_TASKS_t_A_RecordOff=PERIODIC_TASKS_t_A_RecordOff-PERIODIC_TASKS_t_B_RecordOff;
    PERIODIC_TASKS_t_A_ProcessVideo=PERIODIC_TASKS_t_A_ProcessVideo-PERIODIC_TASKS_t_B_RecordOff;
    PERIODIC_TASKS_t_B_RecordOn=PERIODIC_TASKS_t_B_RecordOn-PERIODIC_TASKS_t_B_RecordOff;
    PERIODIC_TASKS_t_B_ProcessVideo=PERIODIC_TASKS_t_B_ProcessVideo-PERIODIC_TASKS_t_B_RecordOff;
    PERIODIC_TASKS_t_C_RecordOn=PERIODIC_TASKS_t_C_RecordOn-PERIODIC_TASKS_t_B_RecordOff;
    PERIODIC_TASKS_t_C_RecordOff=PERIODIC_TASKS_t_C_RecordOff-PERIODIC_TASKS_t_B_RecordOff;
    PERIODIC_TASKS_t_C_ProcessVideo=PERIODIC_TASKS_t_C_ProcessVideo-PERIODIC_TASKS_t_B_RecordOff;
    PERIODIC_TASKS_t_B_RecordOff=25; break;
  case 5: 
    setClock(PERIODIC_TASKS_x,0);
    PERIODIC_TASKS_t_A_RecordOn=PERIODIC_TASKS_t_A_RecordOn-PERIODIC_TASKS_t_B_ProcessVideo;
    PERIODIC_TASKS_t_A_RecordOff=PERIODIC_TASKS_t_A_RecordOff-PERIODIC_TASKS_t_B_ProcessVideo;
    PERIODIC_TASKS_t_A_ProcessVideo=PERIODIC_TASKS_t_A_ProcessVideo-PERIODIC_TASKS_t_B_ProcessVideo;
    PERIODIC_TASKS_t_B_RecordOn=PERIODIC_TASKS_t_B_RecordOn-PERIODIC_TASKS_t_B_ProcessVideo;
    PERIODIC_TASKS_t_B_RecordOff=PERIODIC_TASKS_t_B_RecordOff-PERIODIC_TASKS_t_B_ProcessVideo;
    PERIODIC_TASKS_t_C_RecordOn=PERIODIC_TASKS_t_C_RecordOn-PERIODIC_TASKS_t_B_ProcessVideo;
    PERIODIC_TASKS_t_C_RecordOff=PERIODIC_TASKS_t_C_RecordOff-PERIODIC_TASKS_t_B_ProcessVideo;
    PERIODIC_TASKS_t_C_ProcessVideo=PERIODIC_TASKS_t_C_ProcessVideo-PERIODIC_TASKS_t_B_ProcessVideo;
    PERIODIC_TASKS_t_B_ProcessVideo=25; break;
  case 6: 
    setClock(PERIODIC_TASKS_x,0);
    PERIODIC_TASKS_t_A_RecordOn=PERIODIC_TASKS_t_A_RecordOn-PERIODIC_TASKS_t_C_RecordOn;
    PERIODIC_TASKS_t_A_RecordOff=PERIODIC_TASKS_t_A_RecordOff-PERIODIC_TASKS_t_C_RecordOn;
    PERIODIC_TASKS_t_A_ProcessVideo=PERIODIC_TASKS_t_A_ProcessVideo-PERIODIC_TASKS_t_C_RecordOn;
    PERIODIC_TASKS_t_B_RecordOn=PERIODIC_TASKS_t_B_RecordOn-PERIODIC_TASKS_t_C_RecordOn;
    PERIODIC_TASKS_t_B_RecordOff=PERIODIC_TASKS_t_B_RecordOff-PERIODIC_TASKS_t_C_RecordOn;
    PERIODIC_TASKS_t_B_ProcessVideo=PERIODIC_TASKS_t_B_ProcessVideo-PERIODIC_TASKS_t_C_RecordOn;
    PERIODIC_TASKS_t_C_RecordOff=PERIODIC_TASKS_t_C_RecordOff-PERIODIC_TASKS_t_C_RecordOn;
    PERIODIC_TASKS_t_C_ProcessVideo=PERIODIC_TASKS_t_C_ProcessVideo-PERIODIC_TASKS_t_C_RecordOn;
    PERIODIC_TASKS_t_C_RecordOn=25; break;
  case 7: 
    setClock(PERIODIC_TASKS_x,0);
    PERIODIC_TASKS_t_A_RecordOn=PERIODIC_TASKS_t_A_RecordOn-PERIODIC_TASKS_t_C_RecordOff;
    PERIODIC_TASKS_t_A_RecordOff=PERIODIC_TASKS_t_A_RecordOff-PERIODIC_TASKS_t_C_RecordOff;
    PERIODIC_TASKS_t_A_ProcessVideo=PERIODIC_TASKS_t_A_ProcessVideo-PERIODIC_TASKS_t_C_RecordOff;
    PERIODIC_TASKS_t_B_RecordOn=PERIODIC_TASKS_t_B_RecordOn-PERIODIC_TASKS_t_C_RecordOff;
    PERIODIC_TASKS_t_B_RecordOff=PERIODIC_TASKS_t_B_RecordOff-PERIODIC_TASKS_t_C_RecordOff;
    PERIODIC_TASKS_t_B_ProcessVideo=PERIODIC_TASKS_t_B_ProcessVideo-PERIODIC_TASKS_t_C_RecordOff;
    PERIODIC_TASKS_t_C_RecordOn=PERIODIC_TASKS_t_C_RecordOn-PERIODIC_TASKS_t_C_RecordOff;
    PERIODIC_TASKS_t_C_ProcessVideo=PERIODIC_TASKS_t_C_ProcessVideo-PERIODIC_TASKS_t_C_RecordOff;
    PERIODIC_TASKS_t_C_RecordOff=25; break;
  case 8: 
    setClock(PERIODIC_TASKS_x,0);
    PERIODIC_TASKS_t_A_RecordOn=PERIODIC_TASKS_t_A_RecordOn-PERIODIC_TASKS_t_C_ProcessVideo;
    PERIODIC_TASKS_t_A_RecordOff=PERIODIC_TASKS_t_A_RecordOff-PERIODIC_TASKS_t_C_ProcessVideo;
    PERIODIC_TASKS_t_A_ProcessVideo=PERIODIC_TASKS_t_A_ProcessVideo-PERIODIC_TASKS_t_C_ProcessVideo;
    PERIODIC_TASKS_t_B_RecordOn=PERIODIC_TASKS_t_B_RecordOn-PERIODIC_TASKS_t_C_ProcessVideo;
    PERIODIC_TASKS_t_B_RecordOff=PERIODIC_TASKS_t_B_RecordOff-PERIODIC_TASKS_t_C_ProcessVideo;
    PERIODIC_TASKS_t_B_ProcessVideo=PERIODIC_TASKS_t_B_ProcessVideo-PERIODIC_TASKS_t_C_ProcessVideo;
    PERIODIC_TASKS_t_C_RecordOn=PERIODIC_TASKS_t_C_RecordOn-PERIODIC_TASKS_t_C_ProcessVideo;
    PERIODIC_TASKS_t_C_RecordOff=PERIODIC_TASKS_t_C_RecordOff-PERIODIC_TASKS_t_C_ProcessVideo;
    PERIODIC_TASKS_t_C_ProcessVideo=25; break;

  }
}

/**
 * Transition table.
 */
trans_t TRANS[NB_TRANS] = {
  {true,PERIODIC_TASKS_START,PERIODIC_TASKS_START,-1},
  {true,PERIODIC_TASKS_START,PERIODIC_TASKS_START,-1},
  {true,PERIODIC_TASKS_START,PERIODIC_TASKS_START,-1},
  {true,PERIODIC_TASKS_START,PERIODIC_TASKS_START,-1},
  {true,PERIODIC_TASKS_START,PERIODIC_TASKS_START,-1},
  {true,PERIODIC_TASKS_START,PERIODIC_TASKS_START,-1},
  {true,PERIODIC_TASKS_START,PERIODIC_TASKS_START,-1},
  {true,PERIODIC_TASKS_START,PERIODIC_TASKS_START,-1},
  {true,PERIODIC_TASKS_START,PERIODIC_TASKS_START,-1}
};

/**
 * Location list
 */
loc_t LOC[NB_TRANS+NB_LOC] = {
  0,1,2,3,4,5,6,7,8,tid_NOP/*START*/
};

/**
 * Task bodies
 */
//
//
int A_RecordOn() {
  TASK_BEGIN(A_RecordOn)
// No code pointer for this task

  TASK_END(A_RecordOn)
}

//pc1[0]
//pc1[0]
int A_RecordOff() {
  TASK_BEGIN(A_RecordOff)
// No code pointer for this task

  TASK_END(A_RecordOff)
}

//pc2[1]
//pc2[1]
int A_ProcessVideo() {
  TASK_BEGIN(A_ProcessVideo)
// No code pointer for this task

  TASK_END(A_ProcessVideo)
}

//
//
int B_RecordOn() {
  TASK_BEGIN(B_RecordOn)
// No code pointer for this task

  TASK_END(B_RecordOn)
}

//pc4[3]
//pc4[3]
int B_RecordOff() {
  TASK_BEGIN(B_RecordOff)
// No code pointer for this task

  TASK_END(B_RecordOff)
}

//pc5[4]
//pc5[4]
int B_ProcessVideo() {
  TASK_BEGIN(B_ProcessVideo)
// No code pointer for this task

  TASK_END(B_ProcessVideo)
}

//
//
int C_RecordOn() {
  TASK_BEGIN(C_RecordOn)
// No code pointer for this task

  TASK_END(C_RecordOn)
}

//pc7[6]
//pc7[6]
int C_RecordOff() {
  TASK_BEGIN(C_RecordOff)
// No code pointer for this task

  TASK_END(C_RecordOff)
}

//pc8[7]
//pc8[7]
int C_ProcessVideo() {
  TASK_BEGIN(C_ProcessVideo)
// No code pointer for this task

  TASK_END(C_ProcessVideo)
}

int main(int argc, char **argv) {

  TimesTool_Q2_init();

  execi( &A_RecordOn, 0, NULL, 2, SMALL_STACK_SIZE);
  execi( &A_RecordOff, 0, NULL, 2, SMALL_STACK_SIZE);
  execi( &A_ProcessVideo, 0, NULL, 2, SMALL_STACK_SIZE);
  execi( &B_RecordOn, 0, NULL, 1, SMALL_STACK_SIZE);
  execi( &B_RecordOff, 0, NULL, 1, SMALL_STACK_SIZE);
  execi( &B_ProcessVideo, 0, NULL, 1, SMALL_STACK_SIZE);
  execi( &C_RecordOn, 0, NULL, 0, SMALL_STACK_SIZE);
  execi( &C_RecordOff, 0, NULL, 0, SMALL_STACK_SIZE);
  execi( &C_ProcessVideo, 0, NULL, 0, SMALL_STACK_SIZE);
/*
 * Reset clock variables
 */
  setClock(PERIODIC_TASKS_x,0);


  execi( &controller, 0, NULL, PRIO_HIGHEST, SMALL_STACK_SIZE);

  cputw(MAKESIG);
  return 0;
}
